# SilkTrace — Cross-Platform PDF Report Generator & Data Export
from pathlib import Path
from datetime import datetime
import pandas as pd
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
    HRFlowable,
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import letter

from src.config import REPORTS_DIR, FABRIC_RECOMMENDATIONS, APP_NAME, APP_VERSION

def create_pdf_report(
    summary_df: pd.DataFrame,
    predicted_class: str,
    confidence: float,
    inspection_time: str,
    user_name: str = "SilkTrace User",
    user_email: str = "",
    model_name: str = "MobileNetV2 Deep Learning",
    recommendation: str = ""
) -> str:
    """
    Generate a professional, publication-quality PDF report for fabric defect inspection or prediction.
    Works seamlessly across Windows and Linux (Render).
    Returns absolute file path string to generated PDF.
    """
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    pdf_file_path = REPORTS_DIR / "inspection_report.pdf"

    doc = SimpleDocTemplate(
        str(pdf_file_path),
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=colors.HexColor('#0f172a'),
        alignment=0
    )

    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#3b82f6')
    )

    h2_style = ParagraphStyle(
        'DocH2',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#1e293b'),
        spaceBefore=12,
        spaceAfter=6
    )

    normal_style = ParagraphStyle(
        'DocNormal',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#334155')
    )

    elements = []

    # Header section
    elements.append(Paragraph(f"<b>{APP_NAME} {APP_VERSION}</b>", title_style))
    elements.append(Paragraph("<b>AI-Powered Smart Textile Manufacturing Intelligence Platform</b>", subtitle_style))
    elements.append(Spacer(1, 10))
    elements.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#3b82f6'), spaceAfter=15))

    # Document details
    elements.append(Paragraph("<b>FABRIC QUALITY INSPECTION & AI ANALYSIS REPORT</b>", h2_style))
    elements.append(Spacer(1, 6))

    meta_data = [
        [Paragraph("<b>Inspection Timestamp:</b>", normal_style), Paragraph(str(inspection_time), normal_style)],
        [Paragraph("<b>Generated By (Operator):</b>", normal_style), Paragraph(f"{user_name} ({user_email})" if user_email else user_name, normal_style)],
        [Paragraph("<b>AI Model Architecture:</b>", normal_style), Paragraph(str(model_name), normal_style)],
        [Paragraph("<b>Detected Fabric Condition:</b>", normal_style), Paragraph(f"<b>{predicted_class}</b>", normal_style)],
        [Paragraph("<b>Classification Confidence:</b>", normal_style), Paragraph(f"{confidence:.2f}%", normal_style)]
    ]

    meta_table = Table(meta_data, colWidths=[160, 380])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8fafc')),
        ('PADDING', (0,0), (-1,-1), 6),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    elements.append(meta_table)
    elements.append(Spacer(1, 15))

    # Recommendations Section
    if not recommendation:
        recommendation = FABRIC_RECOMMENDATIONS.get(predicted_class, "Inspect warp/weft yarns and perform standard loom calibration.")

    elements.append(Paragraph("<b>AI Recommended Action & Operational Guidance</b>", h2_style))
    elements.append(Paragraph(str(recommendation), normal_style))
    elements.append(Spacer(1, 15))

    # Summary table
    elements.append(Paragraph("<b>Detailed Metrics & Inspection Attributes</b>", h2_style))
    elements.append(Spacer(1, 6))

    if summary_df is not None and not summary_df.empty:
        raw_data = [summary_df.columns.tolist()] + summary_df.values.tolist()
        table_data = [[Paragraph(f"<b>{str(cell)}</b>" if row_idx == 0 else str(cell), normal_style) for cell in row] for row_idx, row in enumerate(raw_data)]
    else:
        table_data = [
            [Paragraph("<b>Attribute</b>", normal_style), Paragraph("<b>Value</b>", normal_style)],
            [Paragraph("Defect Class", normal_style), Paragraph(str(predicted_class), normal_style)],
            [Paragraph("Confidence Score", normal_style), Paragraph(f"{confidence:.2f}%", normal_style)]
        ]

    data_table = Table(table_data, colWidths=[200, 340])
    data_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1e293b')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('PADDING', (0,0), (-1,-1), 6),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
        ('BACKGROUND', (0,1), (-1,-1), colors.HexColor('#f1f5f9')),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#f8fafc')]),
    ]))
    elements.append(data_table)
    elements.append(Spacer(1, 20))

    # Footer
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#cbd5e1'), spaceBefore=15, spaceAfter=10))
    footer_text = f"Report generated automatically by {APP_NAME} {APP_VERSION} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}. Confidential & Proprietary."
    elements.append(Paragraph(footer_text, ParagraphStyle('FooterStyle', parent=normal_style, fontSize=8, textColor=colors.HexColor('#94a3b8'), alignment=1)))

    doc.build(elements)
    return str(pdf_file_path)
